name: 'odwhtml'
description: An Open DICOMweb library for browser clients.
version: 0.1.0
author: Jim Philbin <mailto:jfphilbin@gmail.com>
homepage: https://github.com/OpenDICOMweb/html

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
#  dart_to_js_script_rewriter: any
  core:
    path: C:/odw/sdk/core
  markdown: any

transformers:
#- dart_to_js_script_rewriter
